### ISSUE TITLE
Qt dependancy

### ISSUE THREAD

**Issue by JieNanMAXIV** [mxcube/HardwareObjects#14]
TangoLimaVideo.py
LimaVideo.py
MiniDiff.py
The above HwObjs are still using Qub.

Ivars, do you have any ideas or plans already to remove the dependancy?

**Comment by IvarsKarpics** [comment]
Hi,
- LimaVideo.py stays in qt3 version and there is Qt4_LimaVideo.py.
- TangoLimaVideo.py could be easy rewritten in Qt4 based on LimaVideo.py -> Qt4_LimaVideo.py. 
  The code part that needs to be changed (example from LimaVideo)

``` python
            raw_buffer = image.buffer()
            if self.do_scaling:
                self.scaling.autoscale_min_max(raw_buffer,
                     image.width(), image.height(), self.scaling_type)
                self.do_scaling = False
            valid_flag, qimage = pixmaptools.LUT.raw_video_2_image(raw_buffer,
                        image.width(),image.height(), self.scaling_type, self.scaling)
            if valid_flag:
                if self.cam_mirror is not None:
                    qimage = qimage.mirror(self.cam_mirror[0], self.cam_mirror[1])
```

to:

``` python
             raw_buffer = image.buffer()
            qimage = QtGui.QImage(raw_buffer, image.width(), image.height(),
                                  QtGui.QImage.Format_RGB888)
            if self.cam_mirror is not None:
                qimage = qimage.mirrored(self.cam_mirror[0], self.cam_mirror[1])
```

We don not have tango, so I can not test this.
- MiniDiff. Here we can remove Qub, because in Qt4 version Qt4_GraphicsManager is taking raw snapshots (frame from camera) and scene snapshots (with points, lines etc). There is a need to take snapshots for autocentring: that is done via camera_hwobj. 

for example in EMBLMinidiff:

``` python
  def find_loop(self):
        snapshot_filename = os.path.join(tempfile.gettempdir(), "mxcube_sample_snapshot.png")
        self.camera_hwobj.save_snapshot(snapshot_filename)
        gevent.sleep(0.01)
        info, x, y = lucid.find_loop(snapshot_filename)
```

I assume that also would be a solution for mxcube3.

**Comment by JieNanMAXIV** [comment]
Thanks a lot!!
