### ISSUE TITLE
Git workflow (please read this)

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/HardwareObjects#24]
Hi all,

To avoid possible problems with branching and more time spends on code merge, we should use a common git workflow. I think it is a moment to become more strict. So:
1. master is our development branch
2. 1.0, 2.1., 2.2. are stable versions
3. We set up a new release each 6 months. Shortly before mxcube meeting to see whats new. 
4. Development is based on Pull requests from feature branches or forkes
5. Bug fixes goes to stable branches and are applied also to master (with cherry picks, PR: this needs to be decided).

I think it is useful to **rebase master on 2.2** (apply newest commits from master to 2.2.) and the **force push** 2.2. to master to start with master == 2.2
This applies to HardwareObjects and mxcube.

**Comment by meguiraun** [comment]
hi,
It is always good to define the workflow. However, I am not sure if this flow would be ok for the development of mxcube3. Currently, whenever we have something to add to the HardwareObjects (new mockup, bugfix, new hwobj, etc) we do a PR to the branch 2.2. This is the branch we are always referring to within the mxcube3 development, as we consider it as stable and in agreement between matias needs and our needs (stable and with only the minimum changes for mxcube3).

Our development assumes that all the new features we add are also in 2.2, otherwise our mxcube3 
server will likely fail... If we do pr-s to master, when will those additions appear in 2.2? (or 2.xx). I think once mxcube 3 is mature enough this proposal will fit perfectly but at the current state it is a bit messy to me.

cheers,

**Comment by JieNanMAXIV** [comment]
Hi Ivars,

Thanks for setting up the rules! As there are more people working on it, it's a very good idea and we need to become more strict! 

However, as Mikel said, I'm not sure if it's a good moment for mxcube3 development regarding the HardwareObjects. The problem is that the current mockups in 2.2 does not match up with the real hwobjs in 2.2 and some methods, signals or hwobj mockup are missing. The branch 2.2 is a stable in terms of real hwobjs, but not for the mockups. For mxcube3 dev., we need a stable version to work with, as we are testing it with both mockups and real hwobj, it will be awkward to test it with mockups of the master branch and the real hwobj of 2.2

I will be very happy if you have any suggestions or solutions about this. 

Best,
Jie

**Comment by IvarsKarpics** [comment]
Hi,

Of course it makes no sense to use diverge branches for development and deployment, but at least between developers there should be a common development branch. For me it is fine to use 2.2. also for development now and do push -f to master time to time.
Could I try to rebase master on 2.2 and then push -f to master? 
Would it be fine?

**Comment by JieNanMAXIV** [comment]
Thanks! For me it’s OK with the rebase. I will also rebase the master often in the future.

**Comment by IvarsKarpics** [comment]
Ok, I will try. In principle there are just two commits from my side and they should not break 2.2.

**Comment by IvarsKarpics** [comment]
Now master == 2.2. Could you try to test 2.2. and master? If it is fine we could from now use master as development. What do you think?

**Comment by IvarsKarpics** [comment]
I will add some co-development guidelines to wiki pages.
